### ISSUE TITLE
社区的持久发展

### ISSUE THREAD

**Issue by impactCn** [archguard/archguard#10]
我有以下建议：

1. 能否举行双周会议，明确方向，更多人了解社区发展

2. issue 发布任务，更多人了解项目需求

**Comment by phodal** [comment]
现在  @isixline 正在计划双周会议

issue 的内容也正在准备迁移

**Comment by isixline** [comment]
感谢建议 🙏
后续会有定期的 catch up 和不定期的讨论及 session，形式和频率正在计划中
