### ISSUE TITLE
项目分析后，点击体量维度-过大的类系统报错

### ISSUE THREAD

**Issue by ziyekudeng** [archguard/archguard#101]
![image](https://user-images.githubusercontent.com/42562723/175760736-2a79fcd6-a23a-4eca-84f2-7a7ccdbeb0ed.png)
![image](https://user-images.githubusercontent.com/42562723/175760759-efd91eb8-ca69-47b2-9471-9c67d13742cd.png)

**Comment by phodal** [comment]
参考一下：https://www.cnblogs.com/zjfjava/p/15120260.html 你们用的是 MySQL 什么版本的？

**Comment by ziyekudeng** [comment]
![image](https://user-images.githubusercontent.com/42562723/175760994-53194f04-635d-48e7-80e0-2f73fc1cb9b5.png)


使用的就是项目中 docker-compose中配置的mysql8。
个人对项目背后的架构理念很感兴趣，在试验、学习中。搭建的个人测试环境在，试用。

**Comment by phodal** [comment]
那这个问题就是 SQL 写得不合理，改起来应该很容易，要试试吗？

**Comment by ziyekudeng** [comment]
好哒，我在本地试试。另外本地开发环境搭建有说明问题不？我先在个人电脑上搭建一套开发环境

**Comment by phodal** [comment]
可以参考：https://archguard.org/setup
