### ISSUE TITLE
archguard-backend无法启动

### ISSUE THREAD

**Issue by gonker** [archguard/archguard#103]
**Describe the bug**
通过`curl -s https://raw.githubusercontent.com/archguard/archguard/master/install.sh | bash -s master ` 启动，后端服务无法启动：
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled。

详细报错信息:
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.7.0)

2022-06-29 11:02:23.971 [main] INFO  c.t.archguard.ApplicationKt - Starting ApplicationKt using Java 12-ea on e12269af70d4 with PID 1 (/home/spring/app.jar started by spring in /home/spring)
2022-06-29 11:02:23.978 [main] INFO  c.t.archguard.ApplicationKt - The following 1 profile is active: "debug"
2022-06-29 11:02:30.579 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 8080 (http)
2022-06-29 11:02:30.604 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8080"]
2022-06-29 11:02:30.604 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
2022-06-29 11:02:30.604 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.63]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007f50616309bc, pid=1, tid=7
#
# JRE version: OpenJDK Runtime Environment (12.0+29) (build 12-ea+29)
# Java VM: OpenJDK 64-Bit Server VM (12-ea+29, mixed mode, sharing, tiered, compressed oops, serial gc, linux-amd64)
# Problematic frame:
# v  ~StubRoutines::updateBytesCRC32
#
# Core dump will be written. Default location: /home/spring/core.1
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

```

**Env (please complete the following information):**
CentOS Linux release 7.6.1810 (Core)
Docker version 20.10.6, build 370c289
Docker Compose version v2.6.1

**Comment by phodal** [comment]
宿主机的环境是？如果是 MBP M1 的话，可以参考：https://github.com/archguard/archguard/issues/53

或者参考一下：https://github.com/archguard/archguard/issues/71， 更新一下 docker compose

**Comment by gonker** [comment]
> 宿主机的环境是？如果是 MBP M1 的话，可以参考：#53
> 
> 或者参考一下：[https://github.com/archguard/archguard/issues/71，](https://github.com/archguard/archguard/issues/71%EF%BC%8C) 更新一下 docker compose

compose的官方github没1.41的包了，我更新到了Docker Compose version v2.6.1，还是报同样的错

**Comment by phodal** [comment]
还有一种可能是 CentOS 机器可能有问题，没有测试过：https://github.com/archguard/archguard/issues/47 估计需要构建一个适用于 CentOS 上面的镜像

**Comment by gonker** [comment]
> 还有一种可能是 CentOS 机器可能有问题，没有测试过：#47 估计需要构建一个适用于 CentOS 上面的镜像

对docker版本有要求吗，我的是Docker version 20.10.6, build 370c289

**Comment by phodal** [comment]
虽然是 OpenJDK 的问题，不过也可以升级一下 Docker 版本试试？

**Comment by gonker** [comment]
> 虽然是 OpenJDK 的问题，不过也可以升级一下 Docker 版本试试？

看了下我的版本已经是比较新的了=-=（最新为20.10.17）。一般我习惯先基于alpine+jdk+其他依赖库构建一个基础环境镜像，然后再基于基础镜像构建应用镜像，能避免大多数宿主机环境问题，除非cpu架构不兼容。环境问题有点头痛哈哈，一会我再试试其他办法

**Comment by phodal** [comment]
现在不也是？https://github.com/archguard/archguard/blob/master/Dockerfile ，要不来个 PR，我对这方面也不是非常擅长 。

**Comment by phodal** [comment]
还有问题吗？
