### ISSUE TITLE
疑问：为什么scanner还要通过进程间通信java -jar的方式来运行呢？

### ISSUE THREAD

**Issue by duguyixiaono1** [archguard/archguard#104]
代码调试过程遇到过，本地缓存了scanner_cli.jar文件，server端代码更新，但scanner_cli.jar不是最新。

为什么scanner还要通过进程间通信java -jar的方式来运行呢？

为什么不在ScannerCliClient里直接调用AnalyserDispatcher().dispatch呢？或者通过http服务化？

**Comment by phodal** [comment]
Scanner 拆分出来，主要是为了支持多种场景，类似于 Jenkins 的 Master/slave 模式，scanner 可以在 agent 上独立运行。在这种情况下，可以支持：

1. 多个项目在多个机器上同时 scan
2. 可以集成到 CI/CD 流水线上。
3. 将 Scanner 集成到自己的后端中（非 ArchGuard）


详细，可以看一下 Meetup 2 的内容：https://www.bilibili.com/video/BV1yt4y1x7UR

**Comment by duguyixiaono1** [comment]
2. 哪种方式都可以吧
1和3. 通过http服务化的方式，也能让一个仓库多种分析器并行执行 

另外怎么解决本地缓存scann_cli.jar的问题呢
