### ISSUE TITLE
使用默认docker-compose文件启动，Mysql8告警

### ISSUE THREAD

**Issue by victoryw** [archguard/archguard#106]
**Describe the bug**
使用默认docker-compose文件启动，Mysql8告警
``` linux
mbind: Operation not permitted
mbind: Operation not permitted
mbind: Operation not permitted
mbind: Operation not permitted
mbind: Operation not permitted
mbind: Operation not permitted
mbind: Operation not permitted
mbind: Operation not permitted
```

**Env (please complete the following information):**
 - OS:  macOS Monterey
 - Env: Docker compose、docker-desktop 3.6.0
 - Browser N/A
 - Version N/A

**To Reproduce**
1.  git clone archguard 代码库
2. Go to 'archguard' 目录
3. 执行 docker-compose up
4. 等一会mysql启动
5. See error

**Expected behavior**
不断打印
``` linux
mbind: Operation not permitted
mbind: Operation not permitted
mbind: Operation not permitted
mbind: Operation not permitted
mbind: Operation not permitted
mbind: Operation not permitted
mbind: Operation not permitted
mbind: Operation not permitted
```

**Comment by victoryw** [comment]
> `mbind: Operation not permitted` 应该不是错误原因
> 
> Docker 客户端是 Colima 还是？
> 
> 还有 docker-compose 的版本？
docker客户端
解决方案：https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log
我提PR给你

**Comment by phodal** [comment]
==，这个错误之前没有遇到过，你能确认一下是不是 compose 版本太旧了？
