### ISSUE TITLE
扫描结束后没有任何提示信息

### ISSUE THREAD

**Issue by handongGit** [archguard/archguard#123]
**Describe the bug**
开始扫描结束后，即没有提示扫描成功也没有提示失败

**Env (please complete the following information):**
2.0.0-beta版本的容器环境，官方提供的镜像

**To Reproduce**
1. 进入 子系统分析
2.  新增系统
3. 点击扫描  没有提示最终扫面结果，所有下拉框，新建工程都是灰色不可选中
4. 数据库中的数据已经存在
5. 数据库 表 system_info的scanned一直是NONE 
6. 修改NONE  为“SCANNED” ，可选中，数据也可以显示

**Expected behavior**

**Comment by phodal** [comment]
查看一下容器里的日志呢？会不会是网络没通？

**Comment by handongGit** [comment]
查看日志了，日志显示 “SET SYSTEM INFO * SCAN FLAG TO :SCANNED ”,查看源码应该是ArchitectureDependencyAnalysis.stopScanSystem中的日志，最终更新方法：SystemInfoRepositoryImplupdateSystemInfo.updateSystemInfo，没有更新system_info 的SCANNED列，如下：

 override fun updateSystemInfo(systemInfo: SystemInfo): Int {
        return jdbi.withHandle<Int, Nothing> {
            it.createUpdate(
                "update system_info set " +
                        "system_name = :systemName, " +
                        "repo = :repo, " +
                        "username = :username, " +
                        "password = :password, " +
                        "repo_type = :repoType, " +
                        "quality_gate_profile_id = :qualityGateProfileId, " +
                        "threshold_suite_id = :badSmellThresholdSuiteId, " +
                        "branch = :branch, " +
                        "language = :language, " +
                        "code_path = :codePath, " +
                        "workdir = :workdir " +
                        "where id = :id"
            )
                .bindBean(systemInfo)
                .execute()
        }
    }
