### ISSUE TITLE
columns in GROUP BY clause

### ISSUE THREAD

**Issue by ariesfly** [archguard/archguard#128]
![image](https://user-images.githubusercontent.com/1968192/219284764-a99fe156-8a6d-4eb0-b407-90107c579019.png)

java.sql.SQLSyntaxErrorException: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'archguard.code_method.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

解析后日常报错，这个sql似乎写错了

**Comment by phodal** [comment]
来个 PR ？

**Comment by ariesfly** [comment]
我先用比较暴力的 弄了，sql 去掉了  id，system_id
然后 JClassPO 构建时候 这两个加了个默认值 “” 和 0.  

报错 是OK，但不好评估 默认值影响。先跑着评估下产品

多了解些 这个系统 我再看怎么PR好点。
