### ISSUE TITLE
没有“依赖分析”

### ISSUE THREAD

**Issue by qiankangjian** [archguard/archguard#130]
![image](https://user-images.githubusercontent.com/33289104/221140660-5c939df9-9cce-41b7-88e8-2898732f0d72.png)
我用的2.0.0版本，没有“依赖分析”，之前的版本有这一项吗？如果之前的版本没有，预计啥时候实现呢

**Comment by phodal** [comment]
前端的 bug，这个功能移到外面的 "代码分析“ 里了。

我记得修了，有可能是 release 没有成功。

**Comment by qiankangjian** [comment]
感谢

**Comment by qiankangjian** [comment]
感谢
