### ISSUE TITLE
您好，能够出一份详细的使用视频教程？

### ISSUE THREAD

**Issue by cfy3133** [archguard/archguard#133]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by phodal** [comment]
能说一个用途吗？现在的功能并不复杂

**Comment by cfy3133** [comment]
主要是想有个具体详细怎么做精准测试的流程哈

**Comment by phodal** [comment]
可以自己录啊

**Comment by cfy3133** [comment]
行吧，谢谢了
