### ISSUE TITLE
database-map页面引用错误

### ISSUE THREAD

**Issue by leochenliu** [archguard/archguard#134]
**Describe the bug**
https://archguard.org/overview 和 https://archguard.org/overview/database-map 两个页面完全一致，猜测是 database-map页面引用错误

**Env (please complete the following information):**
 - Env: Docker compose? Local dev?

**To Reproduce**
<none>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by phodal** [comment]
感谢~，我看看怎么修

**Comment by phodal** [comment]
fixed in 735ed5a41fe3860e1e72639d628f01c8a30148a2
