### ISSUE TITLE
你好，未来是否支持添加关联功能自动生成单元测试、集成测试用例提高测试覆盖率的功能

### ISSUE THREAD

**Issue by cfy3133** [archguard/archguard#137]

**Comment by phodal** [comment]
自动生成测试用例是 AI 做的，在 ArchGuard 中不考虑。在其它我们的工具中已经有一部分实现了：https://github.com/unit-mesh/auto-dev 

<img width="484" alt="图片" src="https://github.com/archguard/archguard/assets/472311/b227fb00-0757-436b-8c16-2e9fe4aa1301">
