### ISSUE TITLE
公司不支持用户名密码登录，当前gitlab系统关闭basic密码认证访问，仅支持ssh key和personal accesstoken方式访问gitlab上项目，其中token身份验证为https方式访问，这种怎么提交系统扫描基本信息

### ISSUE THREAD

**Issue by shiyuanxiu** [archguard/archguard#140]

**Comment by phodal** [comment]
可以考虑：

1. 来 PR 支持这种方式。
2. 使用 Gradle 插件：https://github.com/archguard/archguard-gradle-plugin
3. 使用 Scanner CLI 自定义：https://archguard.org/overview/scanner-cli
