### ISSUE TITLE
Return 500 when clicking search button in '趋势与订阅'

### ISSUE THREAD

**Issue by panguangyao** [archguard/archguard#141]
**Describe the bug**
Return 500 when clicking search button in '趋势与订阅'. 

**Env (please complete the following information):**
 - OS: [Arch Linux]
 - Env: Docker compose
 - Browser [chrome]
 - Version [2.0.7]

**To Reproduce**
1. Go to '趋势与洞察'
2. Choose 'Backend' 'Package Dependencies'
3. Click 'search' button.
![image](https://github.com/archguard/archguard/assets/26272250/a8187a7f-87e7-40bb-9557-51fb5dbf740b)

4. Alert ‘500’ msg.

**Expected behavior**
Show some pictures or datas.

**Screenshots**
![image](https://github.com/archguard/archguard/assets/26272250/2615db1c-9d40-4a36-8e0a-8d1f0ad0a79d)

**Additional context**
 Here are some log messages when I select 'Package Dependencies'.
![image](https://github.com/archguard/archguard/assets/26272250/77176094-5416-4eef-9749-b47891fd0e58)
![image](https://github.com/archguard/archguard/assets/26272250/e6bbe0f6-a660-46bb-97be-ba756e02e46f)

Below logs occur when I select 'class'.
![image](https://github.com/archguard/archguard/assets/26272250/dafbc953-8400-4c00-957f-55dea5405307)
![image](https://github.com/archguard/archguard/assets/26272250/408d2549-fb16-463a-8430-b999678d2bdd)

Thx.

**Comment by panguangyao** [comment]
Good news! Seems to show correct response when I select ‘Issue’ to search. I can't understand.
![image](https://github.com/archguard/archguard/assets/26272250/10c6cd7d-264a-46b9-b2ba-9ec05a4eb152)

**Comment by phodal** [comment]
看上去 systemId=:id 和 AND 之间少了一个空格，欢迎来 PR
