### ISSUE TITLE
关于 analyser_diff_changes-2.1.4-all.jar 的使用问题

### ISSUE THREAD

**Issue by FightingChu** [archguard/archguard#144]
1：background
本人菜鸟一枚，入职某公司后，任务是把公司修改版的 analyser_diff_changes-2.1.4-all.jar 加入到代码中并实现其功能，也就是[ 方法到sql ]的链路调用

2：question
我把 analyser_diff_changes-2.1.4-all.jar 加载到本地仓库并调用的话，会出现 jakarta.servelet. . . . 根据查阅是高版本jdk才有这个功能，而公司使用的为 jdk8，并且是自封框架，所以没有办法做到兼容jakarta及其相关的功能的实现。

3：demand
我在自己电脑下载官方提供的 analyser_diff_changes-2.1.4-all.jar ，在 jdk8 的环境使用 java -jar 方式是可以出现 hello  analyser字样的(公司提供的在java -jar模式会提示main函数丢失)，所以我想知道 analyser_diff_changes-2.1.4-all.jar 在java代码中的调用示例，以及相关环境，可否提供一下。。。我再看看能否找到方法兼容公司修改后的jar。。

4：万分谢谢！

**Comment by phodal** [comment]
可以直接使用  ArchGuard 提供的[ maven  包](https://central.sonatype.com/artifact/org.archguard.scanner/analyser_diff_changes?smo=true)

参考：

https://github.com/archguard/archguard/blob/049f3cc8f2c0e2c34e65bb0049f645caa5be9bf8/analyser_diff_changes/src/main/kotlin/org/archguard/scanner/analyser/DiffChangesAnalyser.kt#L9-L24 的实现

**Comment by FightingChu** [comment]
谢谢

**Comment by FightingChu** [comment]
谢谢
