### ISSUE TITLE
Archguardb部署之后扫描项目失败-日志显示两个错误

### ISSUE THREAD

**Issue by wenruiShi** [archguard/archguard#145]
错误信息：slow sql，OutOfMemoryError

日志截图：
![image](https://github.com/archguard/archguard/assets/27405290/7dde68be-02ca-41ef-95f3-2cd19eca324b)
![image](https://github.com/archguard/archguard/assets/27405290/c96cdf0f-91ed-4e2c-9661-d30447823d00)

安装过程说明：
1、环境为centerOS7
2、安装jdk，版本为java 17.0.11 2024-04-16 LTS
3、安装InfluxDB，版本为InfluxDB v1.8.4 (git: 1.8 bc8ec4384eed25436d31045f974bf39f3310fa3c)
4、安装docker，版本为Docker version 26.1.2, build 211e74b
5、安装Docker Compose，版本为Docker Compose version v2.27.0
6、进入后端目录archguard下执行docker-compose up命令
7、服务成功启动

docker服务执行状态截图：
![image](https://github.com/archguard/archguard/assets/27405290/263cec8a-5212-4ca3-95d3-2a1f8e066559)

扫描配置截图：
![image](https://github.com/archguard/archguard/assets/27405290/87c141f2-4b81-485a-b487-c6d11b566ab4)

**Comment by phodal** [comment]
加内存解决不了？

**Comment by wenruiShi** [comment]
感谢，docker-compose.yml增加内存后已正常
![image](https://github.com/archguard/archguard/assets/27405290/f14a8105-a7a6-42bf-b3a8-bf953981e77c)

另有异常信息：
在内网环境，拉取代码时，自动在仓库地址后加上/info/refs信息，导致获取失败
![8a89e834d3a9593419223784a8ffc20](https://github.com/archguard/archguard/assets/27405290/6a74d9a0-204a-4b3e-b4cf-068a8527ce3e)

页面配置：
![c7481e692a8645d37bfaf26da2db9fd](https://github.com/archguard/archguard/assets/27405290/3efb1e5d-d351-4a45-9fbf-9359c0564cc6)
