### ISSUE TITLE
 About the Architecture Indicators ,where could I find the logic impletement source? 

### ISSUE THREAD

**Issue by JioTao** [archguard/archguard#146]
Dear Phodal , I am a newer of  JAVA, My totally  knowledge about java is "hello world"  ，not to speak spring boot or  kotlin,but  for the work need,I am eager to know the  fllow things：
  - 架构指标（单体DONE，分布式DOING）
    - 体量维度：过大的组件
    - 耦合维度：枢纽组件，过深调用，循环依赖
    - 内聚维度：霰弹式修改
    - 冗余维度：冗余元素，过度泛化
    - 质量维度：测试保护
 how to analyze about mentioned indicators fron  source？
I  read the  ReadMe file，it mentioned one important componet "CHAPAI" , where I could find it  apply to this  project

THANKS

**Comment by phodal** [comment]
事实上，可以直接搜索代码：

https://github.com/archguard/archguard/blob/049f3cc8f2c0e2c34e65bb0049f645caa5be9bf8/server/metric-service/src/main/kotlin/org/archguard/threshold/ThresholdKey.kt#L4-L19

然后查看引用就可以了。
