### ISSUE TITLE
如何利用它实现传值污染跟踪？类似一个值游走的过程。

### ISSUE THREAD

**Issue by smarttang** [archguard/archguard#148]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by phodal** [comment]
为什么不直接使用 CodeQL？

**Comment by smarttang** [comment]
因为Arch实现的更加轻量，CodeQL太重了，假设基于它二开，看看难度多大。
