### ISSUE TITLE
Domain（数据成员，模型）守护

### ISSUE THREAD

**Issue by isixline** [archguard/archguard#20]
比如可以对 domain model 的更改进行分析守护

**Comment by isixline** [comment]
但其实有一个问题，怎么定义 domain model，这个在每个项目中的实践都不一样，感觉很难通过工具标准化扫描

**Comment by phodal** [comment]
有一种方式可以，就是通过自定义规则来进行匹配，类似于 ArchUnit 的方式。只是，在微服务架构下，Core Domain 其实应该是一个服务

**Comment by wizardbyron** [comment]
如果参考 DDD 可以这样：
1. 分析依赖。
2. 如果依赖只包含标准库，和自定义库。就标记为领域的类。（领域的类不应该被其它基础设施依赖）
3. 如果依赖包含三方库（redis/kafka/mysql）就标记为基础设施。
4. 应用入口/作为用户界面层。包含特定的conroller 或者 model。
5. 其它都作为应用层。

按照 DDD 这样就可以分开，同时评估基础设施层和应用层的复杂度。
重构的方向是把应用层/基础设施的逻辑反转向领域层，降低应用层和基础设施层的复杂度。

**Comment by phodal** [comment]
嗯 ，现在就是类似的方式来分析的，不过 DDD 有多种方式，模块化 DDD + 分层 DDD。 @DoubleDuckDuck 在设计
