### ISSUE TITLE
m1的mac电脑，通过docker-compose up 运行时，出现错误：no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by Qi-Zou** [archguard/archguard#3]
错误详情如下：
<img width="842" alt="image" src="https://user-images.githubusercontent.com/41335230/161283452-da8b53bf-a65b-45a8-b773-f1d1e92201d7.png">

最终解决办法：
在docker-compose.yml 配置文件中添加如下配置：
    platform: linux/amd64
<img width="600" alt="image" src="https://user-images.githubusercontent.com/41335230/161283858-4080eaf0-cc80-4811-82d5-a2cd8fdb5d2d.png">

**Comment by phodal** [comment]
欢迎来 PR ~
