### ISSUE TITLE
Client exception when send metrics to InfluxDB. 

### ISSUE THREAD

**Issue by JohnnyChen1986** [archguard/archguard#31]
org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{"error":"partial write: unable to parse 'metric_class_coupling,class_name=.ApplicationTest,package_name=,module_name=root,system_id=3 inner_fan_in=0,inner_fan_out=0,outer_fan_in=0,outer_fan_out=0,inner_instability=0.0,inner_coupling=0.0,outer_instability=0.0,outer_coupling=0.0': missing tag value\nunable to parse 'metric_class_coupling,class_name=.ApplicationTest,package_name=,module_name=root,system_id=3 inner_fan_in=0,inner_fan_out=0,outer_fan_in=0,outer_fan_out=0,inner_instability=0.0,inner_coupling=0.0,outer_instability=0.0,outer_coupling=0.0': missing tag value\nunable to parse 'metric_class_coupling,class_name=.ApplicationTest,package_name=,module_name=root,system_id=3 inner_fan_in=0,inner_fan_out=0,outer_fan_in=0,outer_fan_out=0,inner_instability=0.0,inner_coupling=0.0,outer_instability=0.0,outer_coupling=0.0': missing tag value dropped=0"}<EOL>"

**Comment by phodal** [comment]
有重现的步骤，操作系统环境之类的吗？现有这个信息太少了
