### ISSUE TITLE
访问 http://localhost:11080/ ，网页间断性崩溃

### ISSUE THREAD

**Issue by xuexiansen123** [archguard/archguard#35]
扫描代码库一切正常，通过网页访问`http://localhost:11080/ `，网页出现间断性崩溃，未响应，只能重启浏览器，周而复始。
已经做清理浏览器缓存等操作，都没啥改变，请问大家也是这个样子嘛？感谢大佬们的恢回复，抱拳了！！！
![image](https://user-images.githubusercontent.com/61086658/163302904-260460d4-e8a4-4754-bb31-4c982c8e8c51.png)

**Comment by phodal** [comment]
数据量大？

**Comment by xuexiansen123** [comment]
> 数据量大？

很大可能是的，我司代码量相对庞大点，对于代码量少的没有遇到过网页崩溃的问题

**Comment by phodal** [comment]
那应该是总览页的可视化性能问题。短期内应该很难解决，可以尝试换一个性能更好的电脑。

**Comment by xuexiansen123** [comment]
> 那应该是总览页的可视化性能问题。短期内应该很难解决，可以尝试换一个性能更好的电脑。

大佬，还有一个小问题，不知道别人遇到过没。
修改编辑系统信息的时候，有时候这里的仓库密码会自动清除，之前其实已经配置好的，而且保存了
![image](https://user-images.githubusercontent.com/61086658/163305945-0feed843-299d-452e-864c-574cccf2a56c.png)

**Comment by shihai1991** [comment]
> > 那应该是总览页的可视化性能问题。短期内应该很难解决，可以尝试换一个性能更好的电脑。
> 
> 大佬，还有一个小问题，不知道别人遇到过没。 修改编辑系统信息的时候，有时候这里的仓库密码会自动清除，之前其实已经配置好的，而且保存了 ![image](https://user-images.githubusercontent.com/61086658/163305945-0feed843-299d-452e-864c-574cccf2a56c.png)

这个密码我也遇到了，经常要重置。
