### ISSUE TITLE
只能clone master分支

### ISSUE THREAD

**Issue by whitekoolz** [archguard/archguard#36]
配置分支不起作用，首次clone只能clone master分支。

第二次扫描，会设置git参数 remote.origin.fetch 为配置的分支，但是由于这个分支没有被fetch到，所以会报错。

看了源码确实是这个问题。

**Comment by phodal** [comment]
来个 PR 吗？

**Comment by whitekoolz** [comment]
1.5.4

**Comment by phodal** [comment]
默认分支是 master，但是选的不是 master？那我大概懂了
