### ISSUE TITLE
是否考虑结合链路追踪

### ISSUE THREAD

**Issue by lialzm** [archguard/archguard#38]
目前基于纯静态分析的方式实现代码分析,是否考虑对接类似skywalking,动静结合,结果更加准确通用性也比较好

**Comment by phodal** [comment]
嗯，这个在计划里。不过，按现在的开发规模，可能要到下半年才会设计。

**Comment by lialzm** [comment]
如果想要参与一些功能开发的话,需要如何加入呢,我在官网文档没有找到相关说明呢

**Comment by phodal** [comment]
项目刚开源不久，所以文档上缺得比较多。加入开发和其它开源项目是一样的，比如当前的 issue，就是跟踪这个功能的地方，相关的代码可以关联到这里，然后来 PR。我们也有个微信群，也可以直接加入。
