### ISSUE TITLE
maven 工程扫描失败

### ISSUE THREAD

**Issue by DawnSouther** [archguard/archguard#4]
*问题描述*
新增系统时增加maven工程显示扫描失败

*版本信息*
v1.4.5

*操作流程*
1. docker-compose up 启动，启动无异常，数据库等均无报错。
2. 新增系统 
![image](https://user-images.githubusercontent.com/22205542/161433472-4fab7303-5cb6-4c57-81c8-6bcebce9707d.png)

*报错截图*

![image](https://user-images.githubusercontent.com/22205542/161433382-023cd60e-542c-4059-b030-c58947c26141.png)

*问题分析*
1. 进入容器查看，项目已经拉下来了。
2. 看起来好像是临时目录套了两层的问题？而且mvn显示找不到
![image](https://user-images.githubusercontent.com/22205542/161433564-203bc3f5-823c-4845-8a7a-4159f1511bab.png)

**Comment by phodal** [comment]
对啊，这个临时目录好像是有 Bug。

不过，理论上如果你选了 Java 的话，应该是不会运行 mvn 的，是不是之前选了 JVM?

**Comment by phodal** [comment]
已添加了提示：https://github.com/archguard/archguard-frontend/commit/16c023298e8b583c6d3454860248d6241bebf276

**Comment by DawnSouther** [comment]
然后我改成java了重新扫描，但是啥都没有？
我确定我这个分支是有代码的。
![image](https://user-images.githubusercontent.com/22205542/161434493-0b9f90ef-b274-4a5b-8b0b-b089a6312dff.png)
![image](https://user-images.githubusercontent.com/22205542/161434567-0ed69ae6-69cd-4ee5-9f05-2db715c909d8.png)

我又添加了两个系统，用的都是一样的git地址。
git地址是https的，是因为这个的问题吗？
第一个扫描时报这个错，第二个没报错
![image](https://user-images.githubusercontent.com/22205542/161434590-ceeb82a6-35a4-4878-baa5-875343f0a899.png)

**Comment by phodal** [comment]
看上去是没能成功从 GitHub 下载 scanner

**Comment by DawnSouther** [comment]
> 看上去是没能成功从 GitHub 下载 scanner

我想想办法挂个代理试试

**Comment by DawnSouther** [comment]
> 看上去是没能成功从 GitHub 下载 scanner

ok可以了，我把jar替换后可以扫描出来。

非常感谢

**Comment by yesgit** [comment]
> > 看上去是没能成功从 GitHub 下载 scanner
> 
> ok可以了，我把jar替换后可以扫描出来。
> 
> 非常感谢

请问scanner的jar放在哪里就不用下载了？

**Comment by DawnSouther** [comment]
@yesgit archguard-backend容器里面，和app.jar放同级
