### ISSUE TITLE
工程扫描报错：UnknownHostException: mybatis.org

### ISSUE THREAD

**Issue by boomshakalakawoo** [archguard/archguard#44]
内网环境，请问应如何解决下图报错：
![Uploading 4C57B555-F4A1-41BA-9B0C-8FEF5B66FE48.jpeg…]()

**Comment by phodal** [comment]
看不到图啊，是不是下载不到 Scanner，参照一下：https://archguard.org/faq

**Comment by boomshakalakawoo** [comment]
![D9E0FC1E-6C21-46D2-A21C-86A299D2E873](https://user-images.githubusercontent.com/18066271/163809494-36b3eec0-413b-411e-a1a2-4543f955ed51.jpeg)

**Comment by phodal** [comment]
理解了，这个好像是 MyBatis 解析时候的 bug，应该是解析 DOCTYPE 的时候出错了。

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
```

理论上可能是上面的 `http://mybatis.org/dtd/mybatis-3-mapper.dtd` 在内网的时候报错。

**Comment by phodal** [comment]
在 [https://github.com/archguard/scanner/commit/1aaef984c8e717204b32202b2a71a8461c1c2c82](https://github.com/archguard/scanner/commit/1aaef984c8e717204b32202b2a71a8461c1c2c82) 修复了，预计下个版本发布

1.6.1 版本的 scanner（如果在Docker Compose 里，可以参考一下 FAQ：[https://archguard.org/faq](https://archguard.org/faq) 来更新 Scanner）也可以在离线版本下使用

**Comment by boomshakalakawoo** [comment]
![截屏2022-04-19 上午10 28 44](https://user-images.githubusercontent.com/18066271/163908378-fe0e07df-1ab7-4aaa-9d50-ca2b0bc3c616.png)
理论上可能是上面的 http://mybatis.org/dtd/mybatis-3-mapper.dtd 在内网的时候报错。能确认一下，是不是和上面的 DOCTYPE 一致吗？——一致，scanner1.6.1 已经修复了是吗？

**Comment by phodal** [comment]
对，1.6.1 做了个全局的 try-catch。

你们线上不用 MyBatis 吗？一般不是会改为 classpath，还是只在本地用？
