### ISSUE TITLE
分布式架构治理模型

### ISSUE THREAD

**Issue by YuqingHuang** [archguard/archguard#45]
针对分布式架构，比如微服务架构、以及大型组织范围内的分布式系统，进行架构治理的功能。
包括架构评估、度量趋势等

**Comment by phodal** [comment]
理论上，从模式上，我们应该还能获取到下面的数据：

- 开发方法。瀑布 or 敏捷。
- 开发流程。feature branch、based-branch
- 架构风格。分层架构（ArchGuard）
  - pipes and filter。数据流，Kafka
- 框架 => 总结点（Frozen Spot）或者热点（hot spot）。识别 Interface 和变更等。
