### ISSUE TITLE
软件架构是多层次的，架构治理守护也因该如此。

### ISSUE THREAD

**Issue by HuangDayu** [archguard/archguard#46]
《代码精进之路》一书中，将软件架构划分为业务架构，应用架构、系统架构（我更愿意称职为服务架构）、数据架构、物理架构和运维架构，我觉得还应该补充上技术架构和工程架构。

所以，ArchGuard来说，架构是指什么架构呢？对于开发态来说，也许是在讲应用架构、系统架构和工程架构。

因此，我建议ArchGuard将架构分为应用架构、服务架构、和工程架构更利于使用者对于架构守护的理解。

 - 应用架构：分层架构、六边形架构、洋葱架构、整洁架构、COLA架构等，它评估的维度可能有是否符合架构规范（类似ArchUnit）、架构复杂度等

 - 服务架构（系统架构）：单体架构、SOA架构、分布式架构、微服务架构、事件驱动架构等，它评估的维度可能是否符合服务架构规范（如DDD，中台等思想），调用链路复杂度（如Skywalking的链路分析），服务依赖关系等

 - 工程架构：Maven，Gradle、Ant 等这些应用工程管理工具，它评估的维度可能是依赖关系，体量，质量，耦合，内聚，冗余，测试，代码质量等

简而言之，架构应该从多个层次去分析才有意义。软件领域谈架构，它范围太广，以至于包含很多东西，不利于理解，或者会产生歧义。划分清晰的架构层次能让我们更好的对某一层次的架构进行设计，实施，守护和治理。

以上是本人的一个小建议，欢迎斧正。（Meet Up 上本来想提出来的，但是思路还不清晰，哈哈哈 ）

**Comment by phodal** [comment]
思路挺好的。

我们也在考虑类似的问题。当前，现在的可视化对齐的是 C4，但是 C4 还有一些问题，有些关注的问题，边界不是很清晰。比如，数据库地图有点偏向于是数据架构与应用架构的结合。

我们其实也在讨论类似的问题：

- 结合到业务架构 —— 这可能依赖于，我们创建一些注解，来绑定到系统的各类实现。
- 结合到部署架构  - 在 scanner 中，其中我们也在考虑结合 Jenkins、k8s、dockerfile 来可视化出部署架构，应用的构建速度、依赖等可以间接地指出系统可能的潜在问题。

所以，有可能需要一个类似于此的架构的架构模型。

**Comment by HuangDayu** [comment]
所以，可视化上，应该将架构层次和架构思想体现出来，不同层次的架构应该有自身的评估模型和可视化模型可能会更好。

**Comment by phodal** [comment]
之前漏掉了一个单个代码库的分层架构模式，应该加上来着。

**Comment by phodal** [comment]
move to https://github.com/archguard/archguard/discussions/67
