### ISSUE TITLE
archguard-backend exited with code 139

### ISSUE THREAD

**Issue by shihai1991** [archguard/archguard#47]
**Describe the bug**
docker-compose无法拉起backend容器实例。
![image](https://user-images.githubusercontent.com/9103416/164420294-a9f291f8-654e-406a-9769-65bd0222a324.png)

![image](https://user-images.githubusercontent.com/9103416/164420511-4fff8ca8-35d4-4923-87ef-34fdd3ac83aa.png)

**Env (please complete the following information):**
 - OS: centos7
 - Env: Docker compose
 - Browser: chrome
 - Version: master branch

**Comment by phodal** [comment]
图没上传成功

**Comment by phodal** [comment]
信息太少了，看上去好像是 JDK 的问题。

**Comment by shihai1991** [comment]
> 图没上传成功

updated。帮忙看看啥原因，感觉像是openjdk 12有问题？

**Comment by phodal** [comment]
需要再上拉拉看错误信息，光看错误码，好像不能解决问题。

**Comment by shihai1991** [comment]
![image](https://user-images.githubusercontent.com/9103416/164421244-3cfc8fda-e1e6-49c5-8d81-c7cdfa41fa7f.png)

**Comment by phodal** [comment]
运行在什么系统上这是？之前都没人有过类似的问题。

**Comment by shihai1991** [comment]
就普通centos系统
inux version 3.10.0-957.10.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Mon Mar 18 15:06:45 UTC 2019

**Comment by shihai1991** [comment]
不知道为什么会触发coredump操作~

**Comment by phodal** [comment]
神奇了，应该是环境问题，不知道是是 Docker Compose 的版本问题？或者是 Docker 的问题？

**Comment by shihai1991** [comment]
大佬，你们日常开发测试的环境是用什么版本的docker compose和docker版本，我要不换一个试试，看这个情况不知道openjdk是不是和宿主机有关系。

**Comment by phodal** [comment]
本地开发的时候，都是用 macOS，不过，我都不用 Docker。要不试试手动进去运行一下看会不会有问题？

**Comment by shihai1991** [comment]
还不熟悉你们的代码流和相关工具，手动执行gradle拉后端进程直接报错了:(
![image](https://user-images.githubusercontent.com/9103416/164424251-41e3aed0-eac7-426d-852d-29e20197eb21.png)

**Comment by phodal** [comment]
这个是下载 Gradle 出错吧~~，应该是网络有问题，和项目没关系。详细的可以看：https://archguard.org/development

**Comment by phodal** [comment]
可以尝试使用 1.29.2 的 docker compose

**Comment by phodal** [comment]
M1 的问题，其实和这个问题不太一样。M1 是 Docker 的问题，可以新建一个 issue。

**Comment by shihai1991** [comment]
这个我重新找了centos套环境重新安装docker和docker-compose，服务拉起来了。这个初步看和archguard镜像没关系。

**Comment by shihai1991** [comment]
多谢大佬指导。@phodal

**Comment by phodal** [comment]
@awephy 你新建个 M1 的专用 issue 吧，这个就先关了。
