### ISSUE TITLE
扫描后内容为空，日志报错scan jar包不完整

### ISSUE THREAD

**Issue by zhanhengLu** [archguard/archguard#49]
本地虚拟机搭建起来服务，添加系统后，进行扫描后，扫描结果为空，没有数据，查询日志如下：

日志
HEAD is now at a53da432 chore: remove project name of docker compose
Removing archguard.log
Removing countTest.log
Removing scm_git_hot_file.txt
From https://gitee.com/luzhanheng/archguard
 * branch              master     -> FETCH_HEAD
Already up to date.
Current branch master is up to date.
Error: Invalid or corrupt jarfile scan_sourcecode.jar
jar 包不完整，请尝试连接 VPN 下载。访问： https://archguard.org/docs/faq.html 了解更多
Error: Invalid or corrupt jarfile scan_git.jar
jar 包不完整，请尝试连接 VPN 下载。访问： https://archguard.org/docs/faq.html 了解更多
Error: Unable to access jarfile scan_test_badsmell.jar
下载 Scanner 可能出错，请尝试连接 VPN 下载。访问： https://archguard.org/docs/faq.html 了解更多

随后我进入backend的docker容器内部，进入/home/spring目录下，查看存在scan等jar包，如下
~ $ ls -l
total 63068
-rw-r--r--    1 root     root      58272645 Apr 13 21:02 app.jar
-rw-r--r--    1 spring   spring     3767698 Apr 21 14:19 scan_git-1.5.0-all.jar
-rw-r--r--    1 spring   spring      605579 Apr 21 14:15 scan_sourcecode-1.5.0-all.jar
-rw-r--r--    1 spring   spring     1932680 Apr 21 14:21 scan_test_badsmell-1.4.5-all.jar
~ $ pwd
/home/spring

请大佬指教

**Comment by phodal** [comment]
还是 jar 包不完整啊~，删了重新下载，可能就好了

**Comment by zhanhengLu** [comment]
删啥？docker容器？镜像？

**Comment by phodal** [comment]
删除 /home/spring 下的 `scan_**.jar`

**Comment by zhanhengLu** [comment]
能在gitee仓库上传scan_**.jar包吗，gitee只有源码，没有release

**Comment by phodal** [comment]
已上传：https://gitee.com/archguard/scanner
