### ISSUE TITLE
failed to scan xxxxScanner

### ISSUE THREAD

**Issue by shihai1991** [archguard/archguard#50]
我不确定是不是因为我们公司内部网络限制导致下载部分scanner异常？

![image](https://user-images.githubusercontent.com/9103416/164581070-efa17128-4e39-4db6-9fb5-2943e51be907.png)

**Comment by phodal** [comment]
是的，参考：[ProjectController.kt](https://archguard.org/faq#failed-to-scan-gitsourcescanner)

**Comment by shihai1991** [comment]
收到，感谢。

**Comment by shihai1991** [comment]
还是不行，实际我看是有git扫描记录的
![image](https://user-images.githubusercontent.com/9103416/164586722-7de61e22-4e5b-4c63-a65d-285208d84197.png)

**Comment by shihai1991** [comment]
有没有可能是我们公司内网设置导致的？我不知道除了下载scanner jar包还会不会有其他访问外部的请求？

**Comment by phodal** [comment]
不会

**Comment by shihai1991** [comment]
不行，按照FAQ，jar包拷贝进去改了版本号也不行

**Comment by shihai1991** [comment]
![image](https://user-images.githubusercontent.com/9103416/164605736-ae8d0323-e5ad-4d6b-a7ac-7ce6e5f5b840.png)

![image](https://user-images.githubusercontent.com/9103416/164605782-2439283f-8f62-46b7-baa0-0c40542bb134.png)

**Comment by phodal** [comment]
版本不对，如果是 1.6 的后端的话，对应的 scanner 是 1.5.0，参考一下：https://archguard.org/release/version-mapping

**Comment by phodal** [comment]
我也在文档上声明一下对应版本吧

**Comment by shihai1991** [comment]
好，多谢。这里是否也需要修改一下
![image](https://user-images.githubusercontent.com/9103416/164611936-3c4c60c1-3ca4-4878-bf0c-18f23a37cbaa.png)

**Comment by phodal** [comment]
嗯，嗯，来个 PR 吗？哈哈

**Comment by shihai1991** [comment]
> 嗯，嗯，来个 PR 吗？哈哈

好的呀：）

**Comment by shihai1991** [comment]
感谢，第一个扫描终于跑通了，多谢了。

![image](https://user-images.githubusercontent.com/9103416/164613830-633ff060-3df8-4a6f-a041-756ff734874f.png)

**Comment by shihai1991** [comment]
> 嗯，嗯，来个 PR 吗？哈哈

https://github.com/archguard/archguard.org/pull/10，我不能添加reviewer，求review&merge。
