### ISSUE TITLE
backend服务一直是unhealthy

### ISSUE THREAD

**Issue by awephy** [archguard/archguard#53]
backend服务一直是unhealthy， docker compose切换到1.29.2也试过了不行

环境：
Mac M1
Docker version 20.10.14, build a224086
docker-compose version 1.29.2, build 5becea4c
<img width="658" alt="image" src="https://user-images.githubusercontent.com/8422746/164607872-3ec1869f-0ce1-44fb-8e17-294e62b87d67.png">

<img width="698" alt="image" src="https://user-images.githubusercontent.com/8422746/164607570-8dab4d58-dd06-4fb0-bae9-0820f32cdaf8.png">

**Comment by phodal** [comment]
M1 比较麻烦，主要是 Docker 对于ARM 的支持问题。建议可以先试试本地 setup 开发环境

**Comment by awephy** [comment]
按照文档中https://archguard.org/development#macm1%E4%B8%AD%E5%A6%82%E4%BD%95%E8%BF%90%E8%A1%8C
在执行第二步，启动docker-compose时，报错container已存在
1. 第一步的结果
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/8422746/164613255-21c8ef55-db4a-4b39-adaf-7e9e5cb59526.png">
2.第二步的截图（修改docker-compose文件确认按照文中的内容改过了）
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/8422746/164613462-59914da4-fd9a-4718-843b-9b80e9bcf64e.png">

**Comment by phodal** [comment]
估计得自己排查一下

**Comment by awephy** [comment]
1. 

>

**Comment by awephy** [comment]
已经解决了，感谢

**Comment by phodal** [comment]
如何解析？升级 Compose ？

**Comment by weiliang-ms** [comment]
我的是报下面的错误

```
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
```

**Comment by phodal** [comment]
@weiliang-ms 你这个问题和 https://github.com/archguard/archguard/issues/47 是完全一样的，应该是 OpenJDK + 宿主机的问题

**Comment by hkcyl123** [comment]
我感觉是jdk的问题，因为m1版本的java 得用zulu 才能运行起来，而且我刚刚也查了一下，m1 docker打包出来的镜像默认是arm，我把代码clone下来后在本地启动时没问题的，所以估计要么是镜像问题，要么就是镜像内的java 环境问题

**Comment by phodal** [comment]
zulu 可以？要来个 PR 说明一下吗？https://github.com/archguard/archguard.org/blob/master/docs/setup/setup.md

**Comment by hkcyl123** [comment]
等我看看做成镜像后确认没问题，我把docker file PR进去

**Comment by hkcyl123** [comment]
毕竟docker 镜像会方便很多

**Comment by hkcyl123** [comment]
![image](https://user-images.githubusercontent.com/23721760/169219769-4814c43e-0a0c-4699-81cb-29f675acf183.png)
所以还是因为镜像本身不支持ARM架构的原因。
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/23721760/169259711-84cd3d8b-d4b7-4f44-a8e0-0b71f2ecd033.png">
经过一下午的努力，终于搞定了。我一会提个PR

**Comment by phodal** [comment]
优秀
