### ISSUE TITLE
method 被调用依赖查询 404，无相关报错日志

### ISSUE THREAD

**Issue by boomshakalakawoo** [archguard/archguard#54]
class的各类依赖关系可查，查询method的被调用依赖时接口404，未看到相关报错日志：
![WechatIMG10](https://user-images.githubusercontent.com/18066271/164616831-94e3cdca-d676-46e9-b075-b45585d75a69.jpeg)

**Comment by phodal** [comment]
浏览器的 Console 里有报错吗？

**Comment by phodal** [comment]
找到问题了，很早以前的 bug
