### ISSUE TITLE
chrome访问直接卡死，我们组3个同事点开都是这种情况，用microsoft edge浏览器打开还好些

### ISSUE THREAD

**Issue by shihai1991** [archguard/archguard#55]

**Comment by shihai1991** [comment]
不清楚是什么原因

**Comment by phodal** [comment]
首页那个图形的计算量比较大 —— 要计算 Git 和源码变更之类的，所以如果 commit 多的时候，容易卡死~

**Comment by phodal** [comment]
关联到  #35

**Comment by phodal** [comment]
改为默认不渲染：https://github.com/archguard/archguard-frontend/commit/451f005ae02ab467cff6fc622be25f20a3666bad
