### ISSUE TITLE
除了git文件分析有结果，其他架构评估、架构分析还是没数据

### ISSUE THREAD

**Issue by shihai1991** [archguard/archguard#56]
![image](https://user-images.githubusercontent.com/9103416/164619639-01863643-e324-4dfc-a2f9-53d7349dae82.png)

![image](https://user-images.githubusercontent.com/9103416/164619872-814e0965-9ab4-4b19-b922-55bee721384a.png)

**Comment by phodal** [comment]
不好意思 TestBadSmell 的版本是：1.4.5，后续会在 https://github.com/archguard/archguard/issues/17 一起处理的

**Comment by shihai1991** [comment]
我就看到git文件变更频率有数据，其他都没有:(，后台报错就看到badsmell

**Comment by phodal** [comment]
选择的语言呢？

**Comment by shihai1991** [comment]
选择的语言是java

**Comment by shihai1991** [comment]
![image](https://user-images.githubusercontent.com/9103416/164622254-fc41eed5-568c-40a9-8747-18ed7877a710.png)

**Comment by phodal** [comment]
模块这部分是原来的 JVM 的功能，在改为静态分析之后，支持不是很好。两种扫描模式，这个差距比较大。如果是单体的话，会比较推荐用 JVM 扫描  —— 但是编译的时候容易挂掉。

**Comment by shihai1991** [comment]
我扫了三个库都是没数据，好。我试试jvm模式试试

**Comment by phodal** [comment]
没有，不建议使用 JVM 模式，三个库没有数据，可能是 Scanner 挂掉了，你重新引入 TestBadSmell 的 jar 包试试

**Comment by shihai1991** [comment]
哦哦，好的，了解。我试试

**Comment by shihai1991** [comment]
还在扫描，不过看日志出了一个错
![image](https://user-images.githubusercontent.com/9103416/164627918-66dfdeef-86d0-42e1-ad09-fa3390ba8944.png)

**Comment by phodal** [comment]
图里敏感信息，我干掉了。

这个错误好像看不出上下文

**Comment by shihai1991** [comment]
> 图里敏感信息，我干掉了。
> 
> 这个错误好像看不出上下文

哦，谢谢。

**Comment by shihai1991** [comment]
错误栈最顶层的是这里开始报错的。
![image](https://user-images.githubusercontent.com/9103416/164630796-22ae09fc-b58d-493d-8bc1-3e1e24cdd497.png)

**Comment by phodal** [comment]
那大概率是 MyBatis 解析挂了，Docker 中的 Scanner 是旧的，需要下一个新的 sourcecode_scanner：https://github.com/archguard/scanner/releases/tag/v1.6.1 替换本地的 Scanner（比如 把 jar 里的 1.6.1 改为 1.6.0）

**Comment by shihai1991** [comment]
> 那大概率是 MyBatis 解析挂了，Docker 中的 Scanner 是旧的，需要下一个新的 sourcecode_scanner：https://github.com/archguard/scanner/releases/tag/v1.6.1 替换本地的 Scanner（比如 把 jar 里的 1.6.1 改为 1.6.0）

好的，收到，多谢。我试试。

**Comment by shihai1991** [comment]
OPS.
![image](https://user-images.githubusercontent.com/9103416/164640833-0d2360a9-0517-4277-89ff-a37af5532305.png)

**Comment by shihai1991** [comment]
没其他异常了，这两处看着有点奇怪。
![image](https://user-images.githubusercontent.com/9103416/164641423-e89e5569-15e1-4e13-b500-c1fd30595233.png)
![image](https://user-images.githubusercontent.com/9103416/164641612-babf1379-3904-4e4e-b51d-c74eb0e17ea2.png)

**Comment by phodal** [comment]
别的是正常的？这个质量指标，我们正在考虑干掉……，因为好多现有工具都有的。

**Comment by shihai1991** [comment]
> 别的是正常的？这个质量指标，我们正在考虑干掉……，因为好多现有工具都有的。

no，都不正常，我就顺手截了一个

**Comment by shihai1991** [comment]
> > 那大概率是 MyBatis 解析挂了，Docker 中的 Scanner 是旧的，需要下一个新的 sourcecode_scanner：https://github.com/archguard/scanner/releases/tag/v1.6.1 替换本地的 Scanner（比如 把 jar 里的 1.6.1 改为 1.6.0）
> 
> 好的，收到，多谢。我试试。

那我这里archguard 1.6.0应该对应改成1.5.0吧？

**Comment by phodal** [comment]
不用，只需要修改 scanner 里的 jar 就行了，`scan_sourcecode-1.6.1.-all.jar` => `scan_sourcecode-1.5.0-all.jar`

**Comment by shihai1991** [comment]
多谢，此问题已经解决，相关数据已经可以看到了。
