### ISSUE TITLE
【idea】除了代码仓维度的架构视图，不知道各位专家有没有考虑过怎么对现网的部署视图架构进行分析

### ISSUE THREAD

**Issue by shihai1991** [archguard/archguard#57]
比如异地容灾是否完善，比如负载均衡比较完善，比如爆炸半径是否足够小

**Comment by phodal** [comment]
现在是在考虑如何结合 k8s、APM（如 Skywalking，https://github.com/archguard/archguard/issues/38）进行分析，但是不在短期的计划里。

@YuqingHuang 有想法没？

**Comment by shihai1991** [comment]
这块我搜了一下谷歌，一下实际能从机房，机架，物理机，虚拟机，容器，进程，进程交互整体评估确实比较少，容器k8s这层好像确实稍微多些，架构感知&评估。

**Comment by phodal** [comment]
move to #38
