### ISSUE TITLE
单个系统其他指数没有数据

### ISSUE THREAD

**Issue by zjjay** [archguard/archguard#60]
我尝试了本地扫描https://github.com/archguard/archguard.git 其他数据是可以展示的。
但是扫描纯java项目，其他数据没有，只有总览里存在数据。
项目地址：https://github.com/matevip/matecloud.git
![1](https://user-images.githubusercontent.com/4170652/165239057-ef515c86-df74-4744-a515-95d9a6194f94.png)

![2](https://user-images.githubusercontent.com/4170652/165239106-6144cd90-f20e-4eb3-9548-8d1316d4abbc.png)

**Comment by phodal** [comment]
可以根据描述来查看问题，有的可能代码里真的没问题。

**Comment by zjjay** [comment]
是我分支对应不正确导致的。
![3](https://user-images.githubusercontent.com/4170652/165247605-bd080456-f104-4d16-90d4-cf800cda4c82.png)

**Comment by zjjay** [comment]
解决了，谢谢
