### ISSUE TITLE
需要修改jar包权限才能执行扫描成功

### ISSUE THREAD

**Issue by kongqueshi** [archguard/archguard#61]
按照文档配置完成后，无法扫描成功。看后台报错日志是无法访问jar包，通过chmod 777后才可以正常扫描。

**Comment by phodal** [comment]
已经修复 https://github.com/archguard/archguard/commit/e3d3110fcadc115291b945f87e80f194b73180c0

**Comment by kongqueshi** [comment]
@phodal 你们这响应够快，秒回

**Comment by ditunes** [comment]
java.io.FileNotFoundException: scan_test_badsmell-1.6.2-all.jar (Permission denied)
archguard-backend   | 	at java.base/java.io.FileInputStream.open0(Native Method) ~[na:na]
archguard-backend   | 	at java.base/java.io.FileInputStream.open(FileInputStream.java:213) ~[na:na]
archguard-backend   | 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155) ~[na:na]
archguard-backend   | 	at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:235) ~[kotlin-stdlib-1.6.10.jar!/:1.6.10-release-923(1.6.10)]
archguard-backend   | 	at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217) ~[kotlin-stdlib-1.6.10.jar!/:1.6.10-release-923(1.6.10)]
archguard-backend   | 	at com.thoughtworks.archguard.scanner.infrastructure.FileOperator.copyTo(FileOperator.kt:10) ~[classes!/:na]
archguard-backend   | 	at com.thoughtworks.archguard.scanner.domain.scanner.javaext.tbs.TestBadsmellTool.copyIntoSystemRoot(TestBadsmellTool.kt:44) ~[classes!/:na]
archguard-backend   | 	at com.thoughtworks.archguard.scanner.domain.scanner.javaext.tbs.TestBadsmellTool.prepareTool(TestBadsmellTool.kt:20) ~[classes!/:na]
archguard-backend   | 	at com.thoughtworks.archguard.scanner.domain.scanner.javaext.tbs.TestBadsmellTool.getTest

**Comment by ditunes** [comment]
还是有的

**Comment by phodal** [comment]
还没发布新版本

**Comment by ditunes** [comment]
我看master 已经是你的修复的代码了···但为啥部署还是挂

**Comment by ditunes** [comment]
我是用本地代码启动的

**Comment by phodal** [comment]
哦，哦，那可能不是一个问题吧。

**Comment by phodal** [comment]
@kongqueshi 新版本已经发布：https://github.com/archguard/archguard/releases/tag/v1.6.5

**Comment by phodal** [comment]
不对啊， @ditunes 你的还是 docker compose 启动的，肯定要去 Docker Hub 拿新的。但是新的是刚发布的，所以你老的肯定是挂的
