### ISSUE TITLE
docker-compose启动backend服务无法访问到mysql网络

### ISSUE THREAD

**Issue by wujun27** [archguard/archguard#69]
**Describe the bug**
docker-compose启动backend服务无法访问到mysql网络
 latest镜像打包的代码感觉数据库配置不对，
spring.datasource.url=jdbc:mysql://archguard-mysql:3306/archguard
配置成了spring.datasource.url=jdbc:mysql://archguard_mysql:3306/archguard

**Screenshots**
backend 启动报错 参考附图：  
![image](https://user-images.githubusercontent.com/3659565/167593353-c5f0f96d-207f-4dbe-933a-c899bc64e8c6.png)

**Comment by phodal** [comment]
镜像里的数据库配置是 archguard-mysql，镜像版本是 1.6.5？

**Comment by wujun27** [comment]
擦。。我不会了。。。docker-compose 我记得会自动更新镜像的啊。。。

**Comment by phodal** [comment]
需要拉到半个月前的版本

**Comment by wujun27** [comment]
![image](https://user-images.githubusercontent.com/3659565/167598868-edf183ae-7c64-46bd-b6b0-d97cd0165fa8.png)

我刚手动pull了镜像下，前端镜像更新到17天前了。
后端镜像拉不下来。。我手动清理再试试

**Comment by wujun27** [comment]
![image](https://user-images.githubusercontent.com/3659565/167599242-d5b2075f-8886-4dd0-b463-a6a8ea05243a.png)

手动拉取backend镜像好了。。。
给我整不会了，docker-compose应该会自动拉取镜像的啊

**Comment by phodal** [comment]
不会~
