### ISSUE TITLE
centos archguard/archguard-backend can not start

### ISSUE THREAD

**Issue by chentaolian** [archguard/archguard#71]
**Describe the bug**
archguard/archguard-backend can not start

**Env (please complete the following information):**
 - OS: [centos ] Alibaba Cloud Elastic Compute Service
 - Env: Docker compose

docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

git clone https://github.com/archguard/archguard
docker-compose up

![image](https://user-images.githubusercontent.com/30924975/169778608-88f75edd-41ab-4b13-80b1-f6e670fd9236.png)

**Comment by phodal** [comment]
我发现问题了，Docker Compose 版本太低

**Comment by chentaolian** [comment]
> 我发现问题了，Docker Compose 版本太低，尝试更新一下试试

要求版本是多少
