### ISSUE TITLE
什么时候支持SQL及数据仓库ETL代码的治理

### ISSUE THREAD

**Issue by dawsongzhao** [archguard/archguard#8]
数仓的SQL规范、SQL主题业务域、SQL重复代码片段治理

**Comment by phodal** [comment]
主要是没有这么大的代码库可以分析，SQL 现在是支持 MySQL，PL/SQL 工作量有点大

**Comment by phodal** [comment]
尝试一下：[https://github.com/sqlfluff/sqlfluff](https://github.com/sqlfluff/sqlfluff)
