### ISSUE TITLE
backend setup exception

### ISSUE THREAD

**Issue by duguyixiaono1** [archguard/archguard#83]
按照[setup文档](https://archguard.org/setup)本地启动，已修改config/infrastructure/docker-compose.local.yml中的root密码，启动gradlew bootrun报错：
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/2703461/172341030-7e61d37b-8387-4ada-8ec6-d5dab8e0a003.png">
求解？

**Comment by phodal** [comment]
需要配置一下 Spring 配置里的 `application-local.properties`  上对应的数据库用户名和密码

**Comment by duguyixiaono1** [comment]
> 需要配置一下 Spring 配置里的 `application-local.properties` 上对应的数据库用户名和密码

thx
