### ISSUE TITLE
project_composition_dependencies的name长度太短了

### ISSUE THREAD

**Issue by duguyixiaono1** [archguard/archguard#84]
![Uploading image.png…]()

**Comment by phodal** [comment]
要来个 PR 修复吗？改个 migration 脚本

**Comment by duguyixiaono1** [comment]
> 要来个 PR 修复吗？加个 migration 脚本

大佬，容我先试用和看看代码，^_^

**Comment by phodal** [comment]
嗯，要 PR 话在 `resources/db/migration` 下就可以了

**Comment by duguyixiaono1** [comment]
> 嗯，要 PR 话在 `resources/db/migration` 下就可以了

好的，我先本地改了试试
