### ISSUE TITLE
The testcase for go project will be support.

### ISSUE THREAD

**Issue by woniupapa** [archguard/archguard#86]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by phodal** [comment]
@woniupapa 我这一周在修 Chapi 的 TypeScript bug 的时候，顺便测试了一下 Go 语言，发现是支持 gin 框架的 [GoMethodCallTest.kt](https://github.com/modernizing/chapi/blob/master/chapi-ast-go/src/test/kotlin/chapi/ast/goast/GoMethodCallTest.kt)
