### ISSUE TITLE
【需求】架构评估和指标分析能排除掉测试类吗？

### ISSUE THREAD

**Issue by duguyixiaono1** [archguard/archguard#92]
需求：

1. 架构评估、指标分析中能不能踢掉单元测试类呢？
![image](https://user-images.githubusercontent.com/2703461/173311502-0021d6da-b1ec-4456-8e8a-c32cbe2fcb45.png)

2. 分模块单测覆盖率等指标考虑吗？

**Comment by duguyixiaono1** [comment]
> 需求 1，理论上在这里应该把这测试干掉的。我想想怎么干掉吧
> 
> 需求 2， 单测覆盖率，需要在编译完才能拿到。后期考虑通过接口来接入，只是暂时没有设计 —— 国内能落地测试的不多。

需求1，通过test目录就可以吧

**Comment by phodal** [comment]
嗯，对，已经加了

**Comment by phodal** [comment]
刚发了个修复版，可以测试一下
