### ISSUE TITLE
想了解ArchGuard的应用情况

### ISSUE THREAD

**Issue by duguyixiaono1** [archguard/archguard#93]
RT

非常想了解ArchGuard在TW或其它公司的应用实践，如何指导设计架构、演进架构、观测架构，需求、设计、开发、运行分别起到什么作用，需要什么流程、机制或资源保障

**Comment by phodal** [comment]
可以在微信群里讨论一下，不过，现在应该用的案例不多。

**Comment by duguyixiaono1** [comment]
嗯，可以沉淀一些实践案例的文档，老板提了一个灵魂拷问的问题：做了这么多，怎么证明能起作用？

**Comment by phodal** [comment]
哈哈，单从 Thoughtworks 比较难沉淀下来案例的，都是客户资料。
