### ISSUE TITLE
亟需：提供 C/C++ 架构功能

### ISSUE THREAD

**Issue by xuexiansen123** [archguard/archguard#96]
查看 https://github.com/archguard/archguard 中 README.md ，语言解析主要是通过[Chapi](https://github.com/modernizing/chapi)完成，所以想请问下大佬，啥时候可以提供 C/C++ 语言的架构度量功能？
![image](https://user-images.githubusercontent.com/61086658/175194123-dfd254b8-3212-48bc-a45c-f98cdc57fc28.png)

**Comment by phodal** [comment]
暂时不在计划里，现在参与到项目的人不够多，腾不出精力来添加新语言支持。你有兴趣参与进来吗？

**Comment by xuexiansen123** [comment]
> 暂时不在计划里，现在参与到项目的人不够多，腾不出精力来添加新语言支持。你有兴趣参与进来吗？

大佬抬爱了，这种专业性的挑战还是需要专业人士搞哇

**Comment by phodal** [comment]
其实也不难，之前已经开过坑了，就是要考虑各种情况：https://github.com/modernizing/chapi/blob/master/chapi-ast-cpp/src/main/kotlin/chapi/ast/cppast/CPPFullIdentListener.kt

**Comment by xuexiansen123** [comment]
持续关注大佬们，期待后续新功能

**Comment by invado** [comment]
怎么参与？

**Comment by phodal** [comment]
@invado 语法的解析是在 Chapi 完成的 => 指的是分析依赖的调用关系，随后在 ArchGuard 中完成解析。

要参考的话，可以先在 https://github.com/modernizing/chapi 中提一个 issue，标题上写明 C++，这样的话，就可以知道这个 task 是有人在做的。等完成了底层之后，就可以在 ArchGuard 看到分析效果了。

Chapi 的 C++ 分析在这里：https://github.com/modernizing/chapi/tree/master/chapi-ast-cpp

**Comment by phodal** [comment]
Chapi  中支持了  C 的宏展开，下个版本，理论上可以有基础的功能
