### ISSUE TITLE
文件数量多时 OutofMemomery

### ISSUE THREAD

**Issue by ziyekudeng** [archguard/archguard#97]
作者大大们辛苦!
      执行一个500M大小的系统扫描,执行超过一个小时仍在扫描中。前台、后台没有报错信息。请问代码执行时间大概有个度量标准不？谢谢
![image](https://user-images.githubusercontent.com/42562723/175331905-200b8f85-16e4-434a-bd58-63292773f038.png)

**Comment by phodal** [comment]
500M 大小是怎么定义的？看上去的日志，好像已经有 exception 产生了？

**Comment by ziyekudeng** [comment]
没想到这么晚，还会被回复，辛苦。500M是代码所在文件夹大小。明天我把全量日志下载下来看一下，看官网文档说需要多等一会儿，因为没有前端报错，就忽略观察日志了。

**Comment by ziyekudeng** [comment]
![image](https://user-images.githubusercontent.com/42562723/175334027-2334ca8c-bbf7-47aa-bb3f-7276202048ec.png)
内存溢出了，这里在哪里可以调整不？

**Comment by ziyekudeng** [comment]
需要调整容器得配置，推荐内存使用多少？我配置16G试试

**Comment by phodal** [comment]
你们现在是多少？我估计 4G 就够了吧，你们现在配置的是多少？

**Comment by ziyekudeng** [comment]
原先是10G。我修改成16G了，重启跑跑试试

**Comment by phodal** [comment]
你们之前统计过行数或者提交次数吗？理论上，只有总行数达到一定的量，或者提交资料比较大的时候，才会 OOM。有点神奇

**Comment by ziyekudeng** [comment]
![image](https://user-images.githubusercontent.com/42562723/175336059-09f8143c-2898-4512-8d6e-30d5c8d1bb24.png)
qi'd启动扫描后1分钟，内存消耗增多到8G。目前容器中只运行了这个镜像。我再观察一下

**Comment by ziyekudeng** [comment]
![image](https://user-images.githubusercontent.com/42562723/175336495-97eca1d5-a1ef-4847-a926-2515f699814b.png)
hai's还是内存溢出了，这个可能需要您辛苦看下，需要配置什么了

**Comment by phodal** [comment]
神奇，表面上看好像是序列化的时候出错了。你这边的 CLI 版本是多少？

**Comment by ziyekudeng** [comment]
CLI版本是指？
![image](https://user-images.githubusercontent.com/42562723/175338142-77332b8e-a423-4d1d-b892-65e8d9e058df.png)
初始化项目，分三次提交，提交的文件个数不少，大约4万个文件（java、sql、css、js、xml）。

**Comment by phodal** [comment]
没有详细的日志，但是我猜测应该是 scan_git 的时候出错了。可以考虑先删一些文件，不过这样至少得删除一半吧？这是一个比较老的单体系统？

**Comment by ziyekudeng** [comment]
对了，还有一点。这是一个ant编译的单体项目，有一些依赖包的存在。有配置项可以排除这些文件不？
![image](https://user-images.githubusercontent.com/42562723/175339999-ffc7e086-43e6-435c-8100-a22a0d6945ab.png)

**Comment by phodal** [comment]
问题应该在这里，估计得考虑分段实现了，对于大数据量 @Anddd7 

https://github.com/archguard/archguard/blob/da1fd7d812ffc03a641b8d9445c0914ef28edef0/scanner_cli/src/main/kotlin/org/archguard/scanner/ctl/client/ArchGuardHttpClient.kt#L41-L55

**Comment by ziyekudeng** [comment]
![image](https://user-images.githubusercontent.com/42562723/175446262-f1da123c-3a2c-4081-a36e-cef97573fb13.png)
![image](https://user-images.githubusercontent.com/42562723/175446386-ad33613f-d0b6-4b6d-97e4-8f52ad4f3bf0.png)
![image](https://user-images.githubusercontent.com/42562723/175446468-46a319f2-e423-4bfe-814f-8f8d62fafe59.png)

1.测试环境：GItlab版本为社区版15.1.0  dcoker版本20.10.17  docker compose版本2.6.0  
2.感谢：感谢晚上的回复

**Comment by phodal** [comment]
感谢提供环境，我在本地测试了一下，就是 序列化大对象的时候导致的 OOM。

**Comment by Anddd7** [comment]
got

**Comment by ziyekudeng** [comment]
![image](https://user-images.githubusercontent.com/42562723/194735408-7dbaa4a0-a15f-4937-8d1f-a785dd3afe91.png)
内存溢出的情况仍然存在，使用的是2.0.0.beat2

**Comment by phodal** [comment]
那应该是序列化的时候 OOM 了
