### ISSUE TITLE
Scan failure: 测试项目扫描后各项指标数据为空,后台没有报错信息

### ISSUE THREAD

**Issue by ziyekudeng** [archguard/archguard#98]
![image](https://user-images.githubusercontent.com/42562723/175538000-730fe0b8-850a-4dc5-8e4b-518d1c86cf77.png)

![image](https://user-images.githubusercontent.com/42562723/175538196-6512a730-17e3-4daa-874a-ee777e3eb819.png)

**Comment by phodal** [comment]
总览是正常的？这个不一定是 bug
