### ISSUE TITLE
mysql source字段类型长度小,导致程序异常

### ISSUE THREAD

**Issue by ziyekudeng** [archguard/archguard#99]
![image](https://user-images.githubusercontent.com/42562723/175754283-2d1bb047-3e7c-4003-97ad-57c605dadcc9.png)
![image](https://user-images.githubusercontent.com/42562723/175754290-46f2875e-26eb-4255-bfda-f9a20335f5ca.png)

**Comment by phodal** [comment]
要来个 PR 修复吗？对应的 migration 脚本在：[https://github.com/archguard/archguard/tree/master/server/src/main/resources/db/migration](https://github.com/archguard/archguard/tree/master/server/src/main/resources/db/migration)

**Comment by ziyekudeng** [comment]
您好,请问参与社区修复的规范是什么?可以在哪里,学习一下。后面提交问题，或者提出PR的话，可以按照规则进行。

**Comment by phodal** [comment]
在这里哈：https://archguard.org/contribute-code
